import { ThemeModeScript } from "flowbite-react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import Header from "./Components/Header";
// import BottomNavigation from "./Components/BottomNavigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Night Porno",
  description: "Generated by create-flowbite-react",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-slate-100 antialiased dark:bg-slate-900`}
      >
        {/* <Header />
        <main className="pt-16 pb-20">
          {children}
         </main>
        <BottomNavigation /> */}

        <main className="pt-16 pb-20">Web is blocked</main>
      </body>
    </html>
  );
}
